### PR TITLE
Use constants for certain data submission form values; RDR-307.

### PR DESCRIPTION
**Pull request by coblej**

### CODE REVIEW

**Comment by coblej** [comment]
This PR creates Submission constants for the form values that are not 'yes' or 'no' and uses those constants instead of literal string values in the non-Javascript portions of the code base.

**Comment by coblej** [comment]
@seanaery Thanks for the review.  If you have thoughts on the Javascript question I asked @mikedaul above, those would be welcome as well.

**Comment by mikedaul** [comment]
@coblej - yeah, we'll need to do something for sure :) I've never tried any of those approaches, but I think [this approach](https://codequizzes.wordpress.com/2013/06/06/rails-javascript-workflow-rendering-javascript-partials/) (linked from the SO question) looks good?

**Comment by seanaery** [comment]
@coblej , @mikedaul  -- I haven't used that technique before (using `data-*` attributes on a dummy `div`), but it does look like a clean and useful way to pass the data.

**Pull request merged**
