### PR TITLE
RDR-312 AxS

### PR DESCRIPTION
**Pull request by mikedaul**

### CODE REVIEW

**Comment by mikedaul** [comment]
These [file](https://github.com/duke-libraries/rdr/pull/191/files#diff-2d98c0cb9c7b20ead4c05d0fedbd9e4f) [changes](https://github.com/duke-libraries/rdr/pull/191/files#diff-4440fba6b5ab2d7538fb89c193cbe182) add to our incurred technical debt - ideally we could get the problems fixed in Hyrax proper via the community, but I believe the tweaks are necessary for passing meeting accessibility requirements at Duke, so I think local fixes are the least-worst option for now.

**Comment by coblej** [comment]
@mikedaul I think you're probably right the need for local patching in the short term.  It is my understanding that the Hyrax Working Group intends to focus on accessibility issues in its next sprint, which I think begins in a week or two.  If you're interested in tracking what they're doing about accessibility in that sprint, you could tune in to the `#hyrax-wg` Samvera Slack channel and/or monitor the issues they're working on at https://github.com/samvera/hyrax/projects once they start that sprint.

**Comment by mikedaul** [comment]
Thanks @coblej! I know there is a list of Hyrax [AxS issues](https://github.com/samvera/hyrax/issues?q=is%3Aissue+is%3Aopen+label%3Aaccessibility-concern) in github, but I've also seen several mentions of a report that was done by an outside group. Do you have any idea where to find that?

**Comment by seanaery** [comment]
@mikedaul This is all really helpful -- thanks for working through it! I approve the merge but I'll also leave some thoughts here for future consideration. Darkening the color palette via the Sass variables makes the label and button elements meet contrast requirements (which is great), but also has the side effect of making the UI a bit drab.

It'd require more CSS work, but we might be able to preserve a vibrant color palette and mind the contrast at the same time. E.g., with the `label` elements:
rdr-a11y

> First column is current app (contrast inaccessible), second is the darkened palette, third is a hybrid alternative. Maybe something similar could be done for `button` and `alert` elements too.

**Comment by mikedaul** [comment]
@seanaery - oh yeah, hybrid approach is miles better! I could work on incorporating that in this PR if you think it's worthwhile...

**Comment by seanaery** [comment]
@mikedaul Up to you -- it could turn out to be relatively simple or... could lead down some gnarly rabbit-holes :-) 

As is, our Bootswatch-based theme doesn't do much to distinguish `button`, `label`, `alert`, `select` elements, so there's a ton of room to improve there. Not sure how this would ultimately play out in detemining e.g., what does `label-success` look like vs. `btn-success` etc.

Whether and where the`label` elements are going to appear in the public UI is still a bit volatile: e.g., esp. if Public they may not ultimately appear at all. Things may also shift on the Hyrax core end over the next month too as @coblej mentioned...

**Comment by mikedaul** [comment]
@seanaery - hmm, good points. Maybe I'll just leave as-is (and drab) for now with plans to brighten things up again once UI elements are less in flux...

**Comment by ad96** [comment]
@mikedaul The spreadsheet, "Hyrax_a11y_compiled_issues**" with Hyrax_AuditIssueReport, may be the list of issues found by the Accessibility360 audit...
https://docs.google.com/spreadsheets/d/11uzoJwPs5zKO2dxiWTvGRihwkcsew3GjmURp2RwdGXM/edit#gid=344730415

**Pull request merged**
