### PR TITLE
Override one method in the Hyrax resource list writer so RDR sitemap …

### PR DESCRIPTION
**Pull request by seanaery**
…will only list URLs for collections & works (not files).

### CODE REVIEW

**Comment by seanaery** [comment]
@coblej , @corylown --

This is a WIP; I'm looking for some feedback on how to approach writing a sitemap in a slightly different way than is currently supported by Hyrax core (namely, not including the file URLs in https://research.repository.duke.edu/resourcelist ). See https://duldev.atlassian.net/browse/RDR-449

The solution here (I think this would be considered a monkey patch) seems to require the least amount of code, but I wonder if this is too brittle and/or an inadvisable pattern. I am also struggling to write a test for this (I'm a bit puzzled by factory_bot).

Alternatives to this approach:
1. Replicate the full https://github.com/samvera/hyrax/blob/master/lib/hyrax/resource_sync/resource_list_writer.rb file from Hyrax core into the RDR codebase and modify the build_files method within the copy of that file.
2. Build a separate sitemap writer within RDR that borrows the same general approach from Hyrax core's ResourceList/sitemap writer but doesn't modify, extend, or override any of it.
3. Build an RDR sitemap writer that takes the output of https://research.repository.duke.edu/resourcelist, filters out the file URLs and published a datasets-only sitemap at e.g., https://research.repository.duke.edu/sitemap.
4. Something else?

Thanks for any insight or ideas you have. Happy to meet up to discuss at any time.

**Comment by coblej** [comment]
@seanaery If I'm interpreting the chart on the Jira issue correctly, then it seems that the sitemap (resourcelist) currently has a little than 17,000 entries.  If that's correct, then the RDR would need to nearly triple in size before the 50,000 limit becomes an issue.  I'm not sure what the current / anticipated growth rate is but watchful waiting might be a reasonable strategy?

If we do need to address it now, I wouldn't do #1 above -- replicating the full class.  That would seem to be the most brittle.

Monkey patching the one method, as the PR does, means you'd need to review the override with each upgrade or, at least, be prepared for it to break.  That said, given that it appears that the Hyrax community plans to address the 50,000 limit at some point (though how soon is unknown), it may be a limited vulnerability (i.e., the patch would presumably be removed at some point).

Not sure how much work is involved in approaches #2 and #3 nor how brittle they would be so I don't have much of an opinion on those.

The only one I wouldn't do is #1.

**Comment by corylown** [comment]
@seanaery I think the monkey patch approach is fine in this case.

**Comment by seanaery** [comment]
@coblej , @corylown -- I added some tests and force-pushed, so this work is now ready for review/merge if you approve.

**Pull request merged**
