### PR TITLE
Restyled & rearranged work show page to improve alignment, usability.…

### PR DESCRIPTION
**Pull request by seanaery**
… Partially addresses RDR-270.

### CODE REVIEW

**Comment by seanaery** [comment]
Screenshots of these revisions in action on Work show, e.g., for an anonymous user vs. an admin.

work-show-admin
work-show-anon

**Comment by seanaery** [comment]
@coblej Great observation -- thanks. The column break issue is compounded by some limitations on how definition elements (`<dl>`, `<dt>`, `<dd>`) can be grouped ([example debate by the WHATWG](https://github.com/whatwg/html/issues/1937)). I think I can probably fix it, but as a future revision that may include overriding some core Hyrax code to wrap the term-definition pairs in an element that can be styled to avoid breaking in the column-split. Before investing the time to research & do that I thought it could be useful to see column-splitting in action for live examples: regardless of the odd split points the team could decide that columnizing is undesired.

**Comment by mikedaul** [comment]
I'm struggling to come up with an elegant way to keep the dt and dd from breaking apart across the flex columns. Maybe try wrapping each pair in a div and use 'break-inside: avoid' or something like that?

**Comment by seanaery** [comment]
@coblej , @mikedaul  -- OK, fixed the column break by wrapping each `dt`+`dd` group in a `<div>` per @mikedaul 's idea. I did the (admittedly repetitive) `<div>` wrap in the [attribute_rows partial](https://github.com/duke-libraries/rdr/pull/153/files#diff-c5b9fa6546857b210ba54d95cf73267a) rather than incurring the cost of duplicating/overriding Hyrax's [attribute_renderer](https://github.com/samvera/hyrax/blob/b5b49944b09e9b97765eb88c65aba3dca4c93788/app/renderers/hyrax/renderers/attribute_renderer.rb#L41) in RDR.

**Pull request merged**
