### PR TITLE
Mint and update ARK's to 'public' status as needed during work creati…

### PR DESCRIPTION
**Pull request by coblej**
…on; RDR-184.

### CODE REVIEW

**Comment by coblej** [comment]
I'm happy to schedule a code review session for this PR if that's desired.  The basic idea is to tie into the `:after_create_concern` Hyrax callback (cf `config/initializers/hyrax_callbacks.rb`) to add a `MintPublishArkJob` that invokes code to mint an ARK for the work if it doesn't already have one and to mark the ARK as `public` if it isn't already `public` (cf. `MintPublishArk` service class).  The `Ark` class in this PR borrows heavily from the `Ddr::Models::PermanentId` class in the DDR stack.

**Comment by coblej** [comment]
@dchandekstark Given your work with Ezid and ARK's in the DDR stack, it might be especially useful if you reviewed this PR if you have time.

**Comment by mikedaul** [comment]
@coblej If you're willing, I'd definitely appreciate a code review session. Thanks!

**Comment by coblej** [comment]
Also, since some of the tests in the test suite are integration tests that actually interact with Ezid, I needed a way to get the Ezid test password to Travis in a secure manner.  So, I made use of this capability -- https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings -- to set the EZID_TEST_PASSWORD as an environment variable in the Travis settings for the RDR project.

**Comment by coblej** [comment]
@mikedaul and others ... I scheduled a code review session for next Tuesday afternoon for whoever wants to participate.  Alternatively, if we finish the Sprint Planning early on Monday, we can do it then if folks are available.

**Pull request merged**
